export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const ADD_CUSTOMER_INFO = 'ADD_CUSTOMER_INFO';
export const GET_CUSTOMER_INFO = 'GET_CUSTOMER_INFO';

export const ADD_CUSTOMER_REG = 'ADD_CUSTOMER_REG';
export const GET_CUSTOMER_REG = 'GET_CUSTOMER_REG';

export const ADD_SURVEY = 'ADD_SURVEY';
export const GET_SURVEY = 'GET_SURVEY';
export const GET_SURVEY_BY_ID = 'GET_SURVEY_BY_ID';

export const ADD_WORK_PARTNER = 'ADD_WORK_PARTNER';
export const GET_WORK_PARTNER = 'GET_WORK_PARTNER';

export const GET_LONG_SERVICES = 'GET_LONG_SERVICES';
export const UPDATE_LONG_SERVICES = 'UPDATE_LONG_SERVICES';

export const GET_SHORT_SERVICES = 'GET_SHORT_SERVICES';
export const UPDATE_SHORT_SERVICES = 'UPDATE_SHORT_SERVICES';

export const GET_ADD_ON_SERVICES = 'GET_ADD_ON_SERVICES';
export const UPDATE_ADD_ON_SERVICES = 'UPDATE_ADD_ON_SERVICES';

export const GET_WORK_PARTNER_ADD_ON_SERVICES = 'GET_WORK_PARTNER_ADD_ON_SERVICES';
export const UPDATE_WORK_PARTNER_ADD_ON_SERVICES = 'UPDATE_WORK_PARTNER_ADD_ON_SERVICES';

export const GET_WORK_PARTNER_LONG_SERVICES = 'GET_WORK_PARTNER_LONG_SERVICES';
export const UPDATE_WORK_PARTNER_LONG_SERVICES = 'UPDATE_WORK_PARTNER_LONG_SERVICES';

export const GET_WORK_PARTNER_SHORT_SERVICES = 'GET_WORK_PARTNER_SHORT_SERVICES';
export const UPDATE_WORK_PARTNER_SHORT_SERVICES = 'UPDATE_WORK_PARTNER_SHORT_SERVICES';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const ADD_NEW_MANAGER = 'ADD_NEW_MANAGER';
export const GET_ALL_MANAGERS = 'GET_ALL_MANAGERS';

export const ADD_NEW_CORDINATOR = 'ADD_NEW_CORDINATOR';
export const GET_ALL_CORDINATORS = 'GET_ALL_CORDINATORS';

export const ADD_ARCHITECT_DESIGNER = 'ADD_ARCHITECT_DESIGNER';
export const GET_ALL_ARCHITECT_DESIGNERS = 'GET_ALL_ARCHITECT_DESIGNERS';

export const ADD_NEW_ENQUIRY = 'ADD_NEW_ENQUIRY';
export const GET_ALL_ENQUIRIES = 'GET_ALL_ENQUIRIES';

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';

