export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const ADD_NEW_SOURCE = 'ADD_NEW_SOURCE';
export const GET_ALL_SOURCES = 'GET_ALL_SOURCES';

export const ADD_NEW_CORDINATOR_TYPE = 'ADD_NEW_CORDINATOR_TYPE';
export const GET_ALL_CORDINATOR_TYPES = 'GET_ALL_CORDINATOR_TYPES';

export const ADD_NEW_CORDINATOR = 'ADD_NEW_CORDINATOR';
export const GET_ALL_CORDINATORS = 'GET_ALL_CORDINATORS';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const ADD_NEW_FACTORY_INFO = 'ADD_NEW_FACTORY_INFO';
export const GET_ALL_FACTORY_INFOS = 'GET_ALL_FACTORY_INFOS';

export const ADD_NEW_STATUS_ACTION = 'ADD_NEW_STATUS_ACTION';
export const GET_ALL_STATUS_ACTIONS = 'GET_ALL_STATUS_ACTIONS';

export const ADD_NEW_STATUS = 'ADD_NEW_STATUS';
export const GET_ALL_STATUSES = 'GET_ALL_STATUSES';

export const ADD_NEW_SNAG_ISSUE = 'ADD_NEW_SNAG_ISSUE';
export const GET_ALL_SNAG_ISSUES = 'GET_ALL_SNAG_ISSUES';

export const ADD_NEW_SNAG_SOLUTION = 'ADD_NEW_SNAG_SOLUTION';
export const GET_ALL_SNAG_SOLUTIONS = 'GET_ALL_SNAG_SOLUTIONS';

export const ADD_NEW_SNAG_ACTION = 'ADD_NEW_SNAG_ACTION';
export const GET_ALL_SNAG_ACTIONS = 'GET_ALL_SNAG_ACTIONS';

export const ADD_NEW_SNAG_COST = 'ADD_NEW_SNAG_COST';
export const GET_ALL_SNAG_COSTS = 'GET_ALL_SNAG_COSTS';

export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';

export const ADD_NEW_WORK_TYPE = 'ADD_NEW_WORK_TYPE';
export const GET_ALL_WORK_TYPES = 'GET_ALL_WORK_TYPES';