export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';

export const ADD_NEW_SOURCE = 'ADD_NEW_SOURCE';
export const GET_ALL_SOURCES = 'GET_ALL_SOURCES';

export const ADD_NEW_CORDINATOR_TYPE = 'ADD_NEW_CORDINATOR_TYPE';
export const GET_ALL_CORDINATOR_TYPES = 'GET_ALL_CORDINATOR_TYPES';

export const ADD_NEW_CORDINATOR = 'ADD_NEW_CORDINATOR';
export const GET_ALL_CORDINATORS = 'GET_ALL_CORDINATORS';

export const ADD_NEW_PRODUCT = 'ADD_NEW_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';

export const ADD_NEW_FACTORY_INFO = 'ADD_NEW_FACTORY_INFO';
export const GET_ALL_FACTORY_INFOS = 'GET_ALL_FACTORY_INFOS';

export const ADD_NEW_STATUS_ACTION = 'ADD_NEW_STATUS_ACTION';
export const GET_ALL_STATUS_ACTIONS = 'GET_ALL_STATUS_ACTIONS';

export const ADD_NEW_STATUS = 'ADD_NEW_STATUS';
export const GET_ALL_STATUSES = 'GET_ALL_STATUSES';

export const ADD_NEW_SNAG_ISSUE = 'ADD_NEW_SNAG_ISSUE';
export const GET_ALL_SNAG_ISSUES = 'GET_ALL_SNAG_ISSUES';

export const ADD_NEW_SNAG_SOLUTION = 'ADD_NEW_SNAG_SOLUTION';
export const GET_ALL_SNAG_SOLUTIONS = 'GET_ALL_SNAG_SOLUTIONS';

export const ADD_NEW_SNAG_ACTION = 'ADD_NEW_SNAG_ACTION';
export const GET_ALL_SNAG_ACTIONS = 'GET_ALL_SNAG_ACTIONS';

export const ADD_NEW_SNAG_COST = 'ADD_NEW_SNAG_COST';
export const GET_ALL_SNAG_COSTS = 'GET_ALL_SNAG_COSTS';

export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';

export const ADD_NEW_WORK_TYPE = 'ADD_NEW_WORK_TYPE';
export const GET_ALL_WORK_TYPES = 'GET_ALL_WORK_TYPES';

export const ADD_NEW_ENQUIRY = 'ADD_NEW_ENQUIRY'
export const GET_ALL_ENQUIRIES = 'GET_ALL_ENQUIRIES'

export const ADD_NEW_ORDER = 'ADD_NEW_ORDER'
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'

export const ADD_NEW_SNAGLIST = 'ADD_NEW_SNAGLIST'
export const GET_ALL_SNAGLISTS = 'GET_ALL_SNAGLISTS'

export const ADD_NEW_CARCASS = 'ADD_NEW_CARCASS'
export const GET_ALL_CARCASSES = 'GET_ALL_CARCASSES'

export const ADD_NEW_SHUTTER = 'ADD_NEW_SHUTTER'
export const GET_ALL_SHUTTERS = 'GET_ALL_SHUTTERS'

export const ADD_NEW_SALES_PERSON = 'ADD_NEW_SALES_PERSON'
export const GET_ALL_SALES_PERSONS = 'GET_ALL_SALES_PERSONS'

export const ADD_NEW_DESIGNER = 'ADD_NEW_DESIGNER'
export const GET_ALL_DESIGNERS = 'GET_ALL_DESIGNERS'

export const ADD_NEW_PLANNER = 'ADD_NEW_PLANNER'
export const GET_ALL_PLANNERS = 'GET_ALL_PLANNERS'

export const ADD_NEW_SITE_SURVEYOR = 'ADD_NEW_SITE_SURVEYOR'
export const GET_ALL_SITE_SURVEYORS = 'GET_ALL_SITE_SURVEYORS'

export const ADD_NEW_ORDER_LIST = 'ADD_NEW_ORDER_LIST'
export const GET_ALL_ORDER_LISTS = 'GET_ALL_ORDER_LISTS'

export const ADD_NEW_FACTORY_ENGINEER = 'ADD_NEW_FACTORY_ENGINEER'
export const GET_ALL_FACTORY_ENGINEERS = 'GET_ALL_FACTORY_ENGINEERS'

export const ADD_NEW_FURNISHI_ORDER = 'ADD_FURNISHI_ORDER'
export const GET_ALL_FURNISHI_ORDERS = 'GET_ALL_FURNISHI_ORDERS'

export const ADD_NEW_PANEL = 'ADD_NEW_PANEL'
export const GET_ALL_PANELS = 'GET_ALL_PANELS'

export const ADD_NEW_ASSISTANT_USER = 'ADD_NEW_ASSISTANT_USER'
export const GET_ALL_ASSISTANT_USERS = 'GET_ALL_ASSISTANT_USERS'

export const GET_HISTORY = 'GET_HISTORY'